FROM python:3.13-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    UV_CACHE_DIR='/var/cache/uv'

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libpq-dev && \
    pip install uv && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY pyproject.toml .

RUN --mount=type=cache,target="$UV_CACHE_DIR" \
    uv pip install --system .

COPY . .

RUN useradd -m -d /src -s /bin/bash app && \
    chown -R app:app /src && \
    chmod +x entrypoints/*

USER app